# Generated by Django 3.2.3 on 2021-05-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='user',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
