# Generated by Django 3.2.3 on 2021-05-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('welcome', '0004_auto_20210517_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('fname', models.CharField(max_length=30, null=True)),
                ('lname', models.CharField(max_length=50, null=True)),
                ('add', models.CharField(max_length=80, null=True)),
                ('pin', models.CharField(max_length=10, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
