# Generated by Django 3.2.3 on 2021-05-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0005_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='num',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
