# Generated by Django 3.2.3 on 2021-05-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0009_tran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tran',
            name='card',
        ),
    ]
