# Generated by Django 3.2.3 on 2021-05-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0010_remove_tran_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tran',
            name='add',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tran',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tran',
            name='cname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tran',
            name='cnum',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='tran',
            name='cvv',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tran',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tran',
            name='expmonth',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tran',
            name='expyear',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='tran',
            name='fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tran',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tran',
            name='zip',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
